/// The single source of CSS truth for the crate.
///
/// Assembled at build time by `build.rs` from `src/tokens.css` (design tokens +
/// shared utility classes) and `src/components/*.css` (one per component), then
/// minified at compile time via `minify_css!` (release-only; dev passes through
/// for readable output). lightningcss's `minify` merges identical selectors
/// across the concatenation, so cross-component dedup is real.
///
/// The actual `const` definition (which invokes `minify_css!` on the assembled
/// CSS wrapped in a raw string literal) is generated by `build.rs` into
/// `OUT_DIR/layout_css.rs` and `include!`d here. This indirection is required
/// because `minify_css!` expects a string *literal* at expansion time, and
/// `include_str!(...)` does not expand to a `LitStr` before the proc-macro runs
/// — so the literal must be produced by the build script.
///
/// All classes are namespaced with `gl-`. Components reference class names from
/// this string; they do not inline their own CSS (the per-`Col` responsive
/// rules in `grid.rs` are the only exception, because they are per-instance).
///
/// Override the design tokens on `:root` to theme the layout.
pub use layout_css::LAYOUT_CSS;

mod layout_css {
    include!(concat!(env!("OUT_DIR"), "/layout_css.rs"));
}