pub const LOREM_IPSUM: &'static str = r#"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id vestibulum lacus. Sed non facilisis quam. Donec sem nisl, imperdiet nec eros eget, tristique sodales diam. Nunc non est facilisis, consequat dolor eu, sollicitudin nisl. Nam elementum facilisis tellus semper consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce tristique, mauris non viverra faucibus, elit nulla ullamcorper sem, malesuada interdum nisl nunc vel metus. Etiam urna lacus, consectetur vel mollis quis, euismod eget tellus. Nulla facilisi. Nulla laoreet eu neque id tincidunt. Vivamus cursus non mauris in malesuada. Nam consectetur feugiat vehicula. Praesent eu dolor turpis.

Mauris id tortor interdum lorem tempus laoreet. Quisque velit magna, vulputate nec lectus a, euismod sodales arcu. Sed congue dapibus arcu, mollis tristique nulla sodales nec. Suspendisse lorem augue, rhoncus sed hendrerit sit amet, commodo a dolor. Praesent vulputate metus ut est congue auctor. Donec lobortis ultrices tincidunt. Cras rutrum augue ut neque posuere, vel aliquam lectus vestibulum. Quisque sagittis enim libero, vel pulvinar lectus venenatis eu. Cras pellentesque iaculis sapien, at pharetra mauris aliquet nec. Proin at magna aliquam, porttitor mauris ac, laoreet nibh. Quisque imperdiet felis vel arcu faucibus, ut lobortis mi viverra. Integer iaculis varius dignissim. Vestibulum bibendum justo at tortor hendrerit bibendum. Donec lacinia pellentesque accumsan. Vestibulum venenatis urna diam, vitae elementum ante eleifend in.

Phasellus sodales, ipsum vitae laoreet porttitor, velit justo consectetur dolor, vitae facilisis sem purus sed est. Fusce vitae justo eu purus elementum feugiat quis posuere justo. Curabitur gravida mauris nunc. Suspendisse in libero magna. Proin nec nulla ut enim condimentum lacinia sed at ex. Phasellus accumsan semper tellus, eu lacinia orci hendrerit eu. Integer venenatis enim vel vulputate rutrum. Sed non diam porta, feugiat urna ut, cursus nibh. Cras dictum convallis dui, nec placerat nulla. Praesent scelerisque convallis nibh. Cras blandit tortor sed lectus pulvinar, et euismod urna facilisis.

Integer nisl tortor, gravida mollis est et, cursus auctor risus. Ut sit amet dignissim purus. Phasellus commodo non tellus maximus sodales. Sed velit nunc, efficitur at lacus in, tempus auctor felis. Curabitur a aliquet velit. Nullam non tortor laoreet, elementum lorem non, condimentum magna. Nullam placerat laoreet eleifend. Nullam placerat dolor eget vulputate mollis. Vestibulum id purus justo. Nullam et fermentum ligula. Nam mollis mauris sit amet efficitur suscipit. Maecenas rutrum rutrum elit nec auctor.

Suspendisse sollicitudin, quam eget pellentesque viverra, nulla dolor iaculis orci, in placerat nisi justo et elit. Nulla viverra venenatis ligula molestie rhoncus. Pellentesque sed velit eros. Aenean faucibus hendrerit rhoncus. Praesent sollicitudin magna diam, id accumsan nibh vulputate non. Integer fringilla varius libero, et finibus diam aliquam lobortis. Donec dictum leo et bibendum aliquam. Fusce hendrerit ullamcorper lacus, vitae blandit dolor dapibus in. Proin vitae pulvinar mauris, in aliquam orci. Morbi pellentesque velit porttitor libero mollis consectetur. Morbi a ex auctor, pellentesque mauris non, suscipit magna. Duis vehicula dui eget orci porta bibendum. Vivamus malesuada sapien vitae volutpat luctus. Morbi vitae convallis enim. Morbi porta metus est, in hendrerit odio convallis rhoncus."#;
